"""Tests for scripts/build_adapters.py and scripts/check_rule_copies.py."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import build_adapters  # noqa: E402
import check_rule_copies  # noqa: E402


def _rendered() -> dict[str, str]:
    return build_adapters.build()


def _doc_outputs() -> dict[str, str]:
    # The document adapters (AGENTS.md, per-host rules files, the opencode
    # README). The npm plugin package carries ladder text too, but its
    # machine files (package.json, TS sources, vendored Python/rules) are
    # exempt from the placeholder/header/guard-note invariants below.
    return {rel: renderer() for rel, renderer in build_adapters.OUTPUTS.items()}


def test_build_produces_every_declared_output():
    rendered = _rendered()
    assert set(rendered) == set(build_adapters.OUTPUTS) | set(
        build_adapters.build_opencode_package()
    )


def test_no_placeholder_survives_rendering():
    # A stray "{" means .format() silently left a placeholder unfilled, or a
    # neutral value itself contains a brace -- either is a real bug.
    for rel_path, content in _doc_outputs().items():
        assert "{" not in content, f"{rel_path} has an unrendered placeholder"
        assert "}" not in content, f"{rel_path} has an unrendered placeholder"


def test_generation_header_present_in_every_output():
    for rel_path, content in _doc_outputs().items():
        assert "Generated by scripts/build_adapters.py" in content, rel_path


def test_no_guard_note_present_in_every_output():
    # Every adapter must say it can't enforce the ladder -- non-negotiable
    # per adapters/CLAUDE.md: "no guard, no Stop check" must be stated.
    for rel_path, content in _doc_outputs().items():
        assert build_adapters.NO_GUARD_NOTE in content, rel_path


def test_cursor_mdc_has_valid_frontmatter():
    content = build_adapters.render_cursor_mdc()
    assert content.startswith("---\n")
    frontmatter = content.split("---", 2)[1]
    assert "alwaysApply: true" in frontmatter


def test_windsurf_md_has_valid_frontmatter():
    content = build_adapters.render_windsurf_md()
    assert content.startswith("---\n")
    frontmatter = content.split("---", 2)[1]
    assert "trigger: always_on" in frontmatter


def test_windsurf_under_the_12000_char_workspace_limit():
    # docs.devin.ai/desktop/cascade/memories, verified 2026-09-15: 12,000
    # chars per workspace rule file.
    assert len(build_adapters.render_windsurf_md()) < 12_000


def test_copilot_instructions_has_no_frontmatter():
    # docs.github.com: repository-wide instructions take no frontmatter,
    # unlike path-specific .github/instructions/*.instructions.md files.
    content = build_adapters.render_copilot_instructions()
    assert not content.startswith("---")


def test_no_comment_lines_render_as_a_heading():
    # Regression: a bare "# text" line outside YAML frontmatter and outside
    # an HTML comment renders as a Markdown H1, not a comment. Caught while
    # building this -- the generation header was originally emitted this
    # way in the Cursor/Windsurf renderers.
    for renderer in (
        build_adapters.render_cursor_mdc,
        build_adapters.render_windsurf_md,
    ):
        content = renderer()
        _fm, body = content.split("---", 2)[1:]
        assert "# Generated by" not in body


def test_agents_md_and_copilot_start_with_the_ladders_own_heading():
    # No redundant wrapper title duplicating rules/ladder.md's own "#
    # Odoo change policy (checkbox)" heading.
    for renderer in (
        build_adapters.render_agents_md,
        build_adapters.render_copilot_instructions,
    ):
        content = renderer()
        body = content.split("-->", 1)[1].strip()
        assert body.startswith("# Odoo change policy (checkbox)")


def test_version_and_edition_placeholders_read_grammatically():
    # Regression: {version}/{edition} are used as short inline nouns in
    # ladder.md ("exist in {version} {edition}", "branch {version}"); an
    # earlier draft substituted full instruction sentences there and broke
    # the surrounding grammar.
    content = build_adapters.render_agents_md()
    assert "may already exist in your project's Odoo version" in content
    assert "OCA module on branch your project's Odoo version." in content


def test_check_rule_copies_passes_when_in_sync(tmp_path):
    build_adapters.main(["--output-dir", str(tmp_path)])
    # check_rule_copies targets adapters/ at the repo root by module-level
    # constant, so point it at our freshly-built tmp_path via monkeypatching
    # the module constant instead of re-importing.
    original = check_rule_copies.ADAPTERS_DIR
    try:
        check_rule_copies.ADAPTERS_DIR = tmp_path
        assert check_rule_copies.main() == 0
    finally:
        check_rule_copies.ADAPTERS_DIR = original


def test_check_rule_copies_detects_drift(tmp_path):
    build_adapters.main(["--output-dir", str(tmp_path)])
    (tmp_path / "AGENTS.md").write_text("stale content, not a fresh render\n", encoding="utf-8")
    original = check_rule_copies.ADAPTERS_DIR
    try:
        check_rule_copies.ADAPTERS_DIR = tmp_path
        assert check_rule_copies.main() == 1
    finally:
        check_rule_copies.ADAPTERS_DIR = original


def test_check_rule_copies_detects_stale_extra_file(tmp_path):
    build_adapters.main(["--output-dir", str(tmp_path)])
    (tmp_path / "leftover.md").write_text("no renderer produces this\n", encoding="utf-8")
    original = check_rule_copies.ADAPTERS_DIR
    try:
        check_rule_copies.ADAPTERS_DIR = tmp_path
        assert check_rule_copies.main() == 1
    finally:
        check_rule_copies.ADAPTERS_DIR = original


def test_check_rule_copies_errors_on_missing_dir(tmp_path):
    original = check_rule_copies.ADAPTERS_DIR
    try:
        check_rule_copies.ADAPTERS_DIR = tmp_path / "does-not-exist"
        assert check_rule_copies.main() == 2
    finally:
        check_rule_copies.ADAPTERS_DIR = original


def test_committed_adapters_match_a_fresh_render():
    # The actual fast-checks assertion: committed adapters/ must never drift.
    assert check_rule_copies.main() == 0


def test_opencode_ts_files_have_generation_header():
    for rel in ("opencode/src/index.ts", "opencode/src/ladder.ts"):
        assert "Generated by scripts/build_adapters.py" in _rendered()[rel]


def test_opencode_ladder_ts_is_the_neutral_full_ladder():
    ts = _rendered()["opencode/src/ladder.ts"]
    assert "export const CHECKBOX_LADDER = [" in ts
    for line in build_adapters._render_ladder().splitlines():
        assert json.dumps(line, ensure_ascii=False) in ts
    assert "{" not in ts.split("export const")[1]
    assert "}" not in ts.split("export const")[1]


def test_opencode_package_json_version_is_synced_with_plugin_json():
    pkg = json.loads(build_adapters.render_opencode_package_json())
    plugin = json.loads((REPO_ROOT / "plugins/checkbox/.claude-plugin/plugin.json").read_text())
    assert pkg["name"] == "checkbox-odoo"
    assert pkg["version"] == plugin["version"]
    assert pkg["main"] == "src/index.ts"
    assert pkg["type"] == "module"


def test_opencode_readme_covers_plugin_and_setup_install_paths():
    content = build_adapters.render_opencode_readme()
    assert "opencode2 plugin add checkbox-odoo" in content
    assert "checkbox setup opencode" in content
    assert build_adapters.NO_GUARD_NOTE in content


def test_vendor_core_matches_plugin_tree_verbatim():
    # The npm plugin runs the bundled CLI through whichever real python3/py/
    # python it finds on PATH; if the copy ever drifted from plugins/checkbox/
    # the package would ship broken code silently. Each vendored file must be
    # byte-identical to its source.
    package = build_adapters.build_opencode_package()
    vendored = [rel for rel in package if rel.startswith("opencode/vendor/")]
    assert vendored, "no vendored files produced"
    for rel in vendored:
        source = REPO_ROOT / "plugins" / "checkbox" / rel.removeprefix("opencode/vendor/")
        assert source.is_file(), f"{rel} has no source at {source}"
        assert source.read_text(encoding="utf-8") == package[rel], rel


def test_vendor_package_ships_launcher_and_ladder_rules():
    package = build_adapters.build_opencode_package()
    assert package["opencode/vendor/bin/checkbox"].startswith("#!/usr/bin/env python3")
    for rel in (
        "opencode/vendor/rules/ladder.md",
        "opencode/vendor/rules/ladder.compact.md",
        "opencode/vendor/rules/risk/18.0.json",
    ):
        assert rel in package


def test_check_rule_copies_detects_drift_in_vendored_file(tmp_path):
    build_adapters.main(["--output-dir", str(tmp_path)])
    (tmp_path / "opencode" / "vendor" / "bin" / "checkbox").write_text(
        "tampered launcher\n", encoding="utf-8"
    )
    original = check_rule_copies.ADAPTERS_DIR
    try:
        check_rule_copies.ADAPTERS_DIR = tmp_path
        assert check_rule_copies.main() == 1
    finally:
        check_rule_copies.ADAPTERS_DIR = original
