"""`checkbox setup <host>` -- one-command install for non-Claude hosts.

docs/ARCHITECTURE.md §9 / phase P9. The easy-install answer to "can we
install this for Cursor/Windsurf/Copilot/OpenCode as easily as
`claude plugin install`?". The payloads are the adapters generated by
scripts/build_adapters.py -- this module only copies/merges them into the
target project and never invents rule text of its own (repo CLAUDE.md
non-negotiable #7).

Stdlib-only like the rest of the core. Not a hook: performs no stdout I/O,
so it stays unit-testable; the CLI (cli.py) owns printing.

Hosts and placements (verified 2026-09-15, sources recorded in
scripts/build_adapters.py's docstring):
- cursor:   .cursor/rules/checkbox.mdc
- windsurf: .windsurf/rules/checkbox.md  (legacy documented path; see the
            generated rule file's copy note for .devin/rules/)
- copilot:  .github/copilot-instructions.md
- opencode: AGENTS.md (repo root), merged if it already exists
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

HOSTS = ("opencode", "cursor", "windsurf", "copilot")

# host -> (path relative to the project root, adapter source path)
_RULE_FILES: dict[str, tuple[str, str]] = {
    "cursor": (".cursor/rules/checkbox.mdc", "cursor/checkbox.mdc"),
    "windsurf": (".windsurf/rules/checkbox.md", "windsurf/checkbox.md"),
    "copilot": (".github/copilot-instructions.md", "copilot/copilot-instructions.md"),
    "opencode": ("AGENTS.md", "AGENTS.md"),
}

# Heading that marks the generated section inside a merged AGENTS.md.
_AGENTS_HEADING = "Odoo change policy (checkbox)"


def adapters_dir() -> Path:
    """Where the generated adapters live.

    In the repo checkout they sit at adapters/ next to the plugin; a bundled
    install can relocate them via CHECKBOX_ADAPTERS_DIR.
    """
    env = os.environ.get("CHECKBOX_ADAPTERS_DIR")
    if env:
        return Path(env)
    return Path(__file__).resolve().parents[4] / "adapters"


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def install(
    host: str,
    project_dir: Path,
    *,
    adapters: Path | None = None,
    dry_run: bool = False,
) -> dict:
    """Copy/merge the generated adapter for `host` into `project_dir`.

    Returns a report dict: {"host", "project_root", "files": [{target,
    action, existed, written, sha256}]}. `action` is one of "write",
    "overwrite", "append" or "skip". Raises ValueError for an unknown host
    and FileNotFoundError when the adapter source is missing.
    """
    if host not in HOSTS:
        raise ValueError(f"unknown host {host!r} -- choose from {', '.join(HOSTS)}")
    source_dir = adapters if adapters is not None else adapters_dir()
    target_rel, source_rel = _RULE_FILES[host]
    source_path = source_dir / source_rel
    if not source_path.is_file():
        raise FileNotFoundError(
            f"generated adapter not found at {source_path} -- install from the "
            "checkbox-odoo repo checkout, or set CHECKBOX_ADAPTERS_DIR"
        )
    content = source_path.read_text(encoding="utf-8")
    target = project_dir / target_rel
    existed = target.is_file()
    existing = target.read_text(encoding="utf-8") if existed else None

    if existed and host == "opencode" and _AGENTS_HEADING in existing:
        action, applied = "skip", existing
    elif existed and host == "opencode":
        action, applied = "append", existing.rstrip("\n") + "\n\n" + content
    elif existed:
        action, applied = "overwrite", content
    else:
        action, applied = "write", content

    written = False
    if not dry_run and action != "skip":
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(applied, encoding="utf-8")
        written = True

    return {
        "host": host,
        "project_root": str(project_dir),
        "files": [
            {
                "target": target_rel,
                "action": action,
                "existed": existed,
                "written": written,
                "sha256": _sha256(applied),
            }
        ],
    }
