#!/usr/bin/env python3
"""Render plugins/checkbox/rules/ladder.md into adapters/ for non-Claude hosts.

docs/ARCHITECTURE.md §9 / plugins/checkbox/CLAUDE.md non-negotiable #7: the
ladder text lives only in rules/ladder.md; every adapter here is generated
from it, never hand-edited. Scope matches §9's stated priority order --
AGENTS.md (read by OpenCode, and as a bonus by many other hosts: Amp, Jules,
Zed, JetBrains Junie, generic agents -- confirmed against a real shipping
multi-host plugin, Ponytail's docs/agent-portability.md, 2026-09-15), Cursor,
Windsurf, GitHub Copilot. Codex's fuller "plugin hooks" treatment (§9 row 3)
is deliberately deferred -- see docs/ARCHITECTURE.md §13's P6 row for why.

Unlike lib/checkbox/ladder.py's render(), which fills placeholders from a
real Profile, every adapter here runs outside any Claude Code hook and can
never see a live profile.json. Placeholders are filled with neutral text
that tells the reader to run `checkbox profile show` -- never a guessed or
baked-in value (adapters/CLAUDE.md's own rule).

Host conventions verified 2026-09-15:
- Cursor: `.cursor/rules/<name>.mdc`, YAML frontmatter `alwaysApply: true`
  (cursor.com/docs/context/rules).
- Windsurf: `.windsurf/rules/<name>.md` (documented as the still-working
  legacy path; `.devin/rules/<name>.md` is the newer preferred path after
  the Windsurf/Devin AI rebrand -- docs.devin.ai/desktop/cascade/memories).
  Frontmatter `trigger: always_on`. 12,000 char limit per file (rendered
  ladder.md is ~2,000 chars, no risk of hitting it).
- GitHub Copilot: `.github/copilot-instructions.md`, plain markdown, no
  frontmatter (docs.github.com/en/copilot/how-tos/configure-custom-instructions).
- OpenCode: reads AGENTS.md automatically; no separate rule file needed for
  the instruction-tier scope this project targets (§9: "OpenCode (AGENTS.md
  + CLI)", not Ponytail's fuller injected-plugin treatment).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RULES_DIR = REPO_ROOT / "plugins" / "checkbox" / "rules"
PLUGIN_JSON = REPO_ROOT / "plugins" / "checkbox" / ".claude-plugin" / "plugin.json"

NEUTRAL_PLACEHOLDERS = {
    "profile_line": (
        "run `checkbox profile show` to see this project's version, edition and hosting"
    ),
    "mode": "full (run `checkbox mode show` to check the current level)",
    # {version}/{edition}/{studio_clause} are used inline as short nouns in
    # ladder.md ("may already exist in {version} {edition}", "on branch
    # {version}", "server actions{studio_clause}") -- a real render fills
    # them with short values like "18.0"/"community" (profile.py), so a
    # neutral render needs matching short phrases, not instruction
    # sentences, or the surrounding grammar breaks. The one-time pointer to
    # `checkbox profile show` already lives in {profile_line} above.
    "version": "your project's Odoo version",
    "edition": "(run `checkbox profile show` for the exact version and edition)",
    "studio_clause": ", Studio (Enterprise)",
    "hosting_clause": (
        "If this project is hosted on Odoo Online, custom Python modules cannot be "
        "installed and rung 6 is unavailable -- run `checkbox profile show` to check "
        "the hosting."
    ),
}

NO_GUARD_NOTE = (
    "This file carries the ladder text only. It cannot enforce it: only the "
    "Claude Code plugin's PreToolUse/PostToolUse/Stop hooks do that. Treat "
    "this as a strong reminder, not a gate."
)


def _plugin_version() -> str:
    import json

    return json.loads(PLUGIN_JSON.read_text(encoding="utf-8"))["version"]


def _render_ladder() -> str:
    template = (RULES_DIR / "ladder.md").read_text(encoding="utf-8")
    return template.format(**NEUTRAL_PLACEHOLDERS).rstrip("\n")


def _generation_header(comment_prefix: str, comment_suffix: str = "") -> str:
    version = _plugin_version()
    return (
        f"{comment_prefix} Generated by scripts/build_adapters.py from "
        f"plugins/checkbox/rules/ladder.md (checkbox v{version}). "
        f"Do not hand-edit -- see plugins/checkbox/../adapters/CLAUDE.md.{comment_suffix}"
    )


def render_agents_md() -> str:
    header = _generation_header("<!--", " -->")
    ladder = _render_ladder()
    return f"""{header}

{ladder}

## CLI

`checkbox` (the plugin's `bin/checkbox`, or `pip install -e .` from the
checkbox-odoo repo for standalone use) supports:

```
checkbox profile show                 # this project's version/edition/hosting
checkbox search "<query>"             # evidence for rung 2 (standard) / rung 5 (module)
checkbox classify <file>              # blast-radius tier for a changed file
checkbox card next-id / validate      # decision card workflow
```

{NO_GUARD_NOTE}
"""


def render_cursor_mdc() -> str:
    # A "# " line outside the frontmatter renders as a Markdown H1, not a
    # comment -- the generation note goes inside the YAML block instead,
    # where "#" is a real comment, and the visible body starts clean.
    header = _generation_header("#")
    ladder = _render_ladder()
    return f"""---
alwaysApply: true
{header}
---

{ladder}

{NO_GUARD_NOTE}
"""


def render_windsurf_md() -> str:
    header = _generation_header("#")
    ladder = _render_ladder()
    return f"""---
trigger: always_on
{header}
---

<!-- Copy destination note: .windsurf/rules/ is the working legacy path as
     of 2026-09-15; Windsurf's docs (post Devin AI rebrand) list
     .devin/rules/ as the preferred one. Copy this file to whichever your
     Windsurf/Devin version reads -- check both if the rule doesn't load. -->

{ladder}

{NO_GUARD_NOTE}
"""


def render_copilot_instructions() -> str:
    header = _generation_header("<!--", " -->")
    ladder = _render_ladder()
    return f"""{header}

{ladder}

{NO_GUARD_NOTE}
"""


def render_opencode_readme() -> str:
    header = _generation_header("<!--", " -->")
    return f"""{header}

# checkbox for OpenCode

OpenCode reads `AGENTS.md` from the repository root automatically -- copy
`adapters/AGENTS.md` (this directory's sibling) to your project's own
`AGENTS.md`, or merge its "Odoo change policy (checkbox)" section into an
existing one.

`checkbox`'s CLI (`checkbox search`, `checkbox classify`, `checkbox card
next-id`/`validate`) works from any shell OpenCode's agent can invoke; see
`AGENTS.md`'s own CLI section for the commands.

{NO_GUARD_NOTE}
"""


OUTPUTS: dict[str, tuple[str, object]] = {
    "AGENTS.md": ("AGENTS.md", render_agents_md),
    "cursor/checkbox.mdc": ("Cursor -- copy to .cursor/rules/checkbox.mdc", render_cursor_mdc),
    "windsurf/checkbox.md": (
        "Windsurf -- copy to .windsurf/rules/checkbox.md (or .devin/rules/)",
        render_windsurf_md,
    ),
    "copilot/copilot-instructions.md": (
        "GitHub Copilot -- copy to .github/copilot-instructions.md",
        render_copilot_instructions,
    ),
    "opencode/README.md": ("OpenCode", render_opencode_readme),
}


def build(output_dir: Path) -> dict[str, str]:
    """Render every adapter. Returns {relative_path: content} without writing
    anything -- callers decide whether to write to disk (build) or diff
    in-memory (check_rule_copies.py)."""
    return {rel_path: renderer() for rel_path, (_label, renderer) in OUTPUTS.items()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        default=str(REPO_ROOT / "adapters"),
        help="Directory to write into (default: adapters/ at the repo root).",
    )
    args = parser.parse_args(argv)
    output_dir = Path(args.output_dir)

    rendered = build(output_dir)
    for rel_path, content in rendered.items():
        dest = output_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        print(f"wrote {dest.relative_to(REPO_ROOT) if dest.is_relative_to(REPO_ROOT) else dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
