// Generated by scripts/build_adapters.py from plugins/checkbox/rules/ladder.md (checkbox v1.2.2). Do not hand-edit -- see plugins/checkbox/../adapters/CLAUDE.md.

import type { Plugin } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"
import { existsSync } from "node:fs"
import { CHECKBOX_LADDER } from "./ladder.js"

const LADDER_MARKER = "Odoo change policy (checkbox)"
const VENDOR_CLI = new URL("../vendor/bin/checkbox", import.meta.url).pathname

// Finds a real Python 3, skipping the Microsoft Store's placeholder
// python3/python alias stubs on Windows: real executable files (not a
// missing command), always under a path containing "WindowsApps", the
// one stable marker for them. Falls through py -3 (the Windows Python
// Launcher, immune to the Store alias, shipped by the official
// python.org installer), then bare python. Mirrors bin/checkbox-hook's
// logic for Claude Code hooks (docs/ARCHITECTURE.md D12) -- this plugin
// doesn't go through hooks.json at all, so it needs its own copy.
function resolveOnPath(name: string): string | null {
  const dirs = (process.env.PATH ?? "").split(process.platform === "win32" ? ";" : ":")
  const exts = process.platform === "win32" ? ["", ".exe"] : [""]
  for (const dir of dirs) {
    if (!dir || dir.includes("WindowsApps")) continue
    for (const ext of exts) {
      const candidate = `${dir}/${name}${ext}`
      if (existsSync(candidate)) return candidate
    }
  }
  return null
}

function findPython(): { cmd: string; args: string[] } {
  const override = process.env.CHECKBOX_PYTHON
  if (override) return { cmd: override, args: [] }
  const python3 = resolveOnPath("python3")
  if (python3) return { cmd: python3, args: [] }
  const py = resolveOnPath("py")
  if (py) return { cmd: py, args: ["-3"] }
  const python = resolveOnPath("python")
  if (python) return { cmd: python, args: [] }
  return { cmd: "python3", args: [] }
}

async function readAll(stream: ReadableStream): Promise<string> {
  return await new Response(stream).text()
}

async function runCli(args: string[], cwd: string): Promise<string> {
  const { cmd, args: pyArgs } = findPython()
  // opencode embeds Bun; spawn deliberately avoids starting a shell.
  const bun = (globalThis as any).Bun
  const proc = bun.spawn({
    cmd: [cmd, ...pyArgs, VENDOR_CLI, ...args],
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  })
  const [out, err] = await Promise.all([readAll(proc.stdout), readAll(proc.stderr)])
  const code = (await proc.exited) as number
  const text = (out || err).trim()
  return code === 0 ? text : `checkbox exited ${code}: ${text}`
}

async function classifyTier(file: string, cwd: string): Promise<string | null> {
  try {
    const out = await runCli(["classify", "--json", file], cwd)
    const parsed = JSON.parse(out)
    return typeof parsed.tier === "string" ? parsed.tier : null
  } catch {
    return null
  }
}

const COMMANDS = ["profile", "search", "classify", "card", "mode", "ladder"] as const

export const CheckboxPlugin: Plugin = async ({ directory }) => ({
  "experimental.chat.system.transform": async (input, output) => {
    if (!output.system.some((block) => block.includes(LADDER_MARKER))) {
      output.system.push(CHECKBOX_LADDER)
    }
  },
  tool: {
    checkbox: tool({
      description:
        "Run the checkbox Odoo change-policy CLI (bundled, stdlib-only Python). "
        "Call it with a checkbox subcommand plus its CLI arguments, passed "
        "verbatim in the args array -- e.g. command = search, args = [purchase "
        "approval]. Commands: profile show, profile detect, search <query>, "
        "classify <file>, card validate <file>, mode show, ladder render. Add "
        "--json for machine-readable output.",
      args: {
        command: tool.schema.enum(COMMANDS).describe("checkbox subcommand"),
        args: tool.schema
          .array(tool.schema.string())
          .optional()
          .describe("arguments for the subcommand; [] when none"),
      },
      async execute(input, ctx) {
        return await runCli([input.command, ...(input.args ?? [])], ctx.directory)
      },
    }),
  },
  "tool.execute.after": async (input, output) => {
    if (input.tool !== "write" && input.tool !== "edit") return
    const file =
      input.args?.filePath ?? input.args?.path ?? input.args?.file
    if (typeof file !== "string") return
    const tier = await classifyTier(file, directory)
    if (tier) output.title = `checkbox: ${tier}`
  },
})

export default CheckboxPlugin
