// Generated by scripts/build_adapters.py from plugins/checkbox/rules/ladder.md (checkbox v1.1.1). Do not hand-edit -- see plugins/checkbox/../adapters/CLAUDE.md.

import type { Plugin } from "@opencode-ai/plugin"
import { tool } from "@opencode-ai/plugin"
import { CHECKBOX_LADDER } from "./ladder.js"

const LADDER_MARKER = "Odoo change policy (checkbox)"
const VENDOR_CLI = new URL("../vendor/bin/checkbox", import.meta.url).pathname

async function readAll(stream: ReadableStream): Promise<string> {
  return await new Response(stream).text()
}

async function runCli(args: string[], cwd: string): Promise<string> {
  const python = process.env.CHECKBOX_PYTHON ?? "python3"
  // opencode embeds Bun; spawn deliberately avoids starting a shell.
  const bun = (globalThis as any).Bun
  const proc = bun.spawn({
    cmd: [python, VENDOR_CLI, ...args],
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  })
  const [out, err] = await Promise.all([readAll(proc.stdout), readAll(proc.stderr)])
  const code = (await proc.exited) as number
  const text = (out || err).trim()
  return code === 0 ? text : `checkbox exited ${code}: ${text}`
}

async function classifyTier(file: string, cwd: string): Promise<string | null> {
  try {
    const out = await runCli(["classify", "--json", file], cwd)
    const parsed = JSON.parse(out)
    return typeof parsed.tier === "string" ? parsed.tier : null
  } catch {
    return null
  }
}

const COMMANDS = ["profile", "search", "classify", "card", "mode", "ladder"] as const

export const CheckboxPlugin: Plugin = async ({ directory }) => ({
  "experimental.chat.system.transform": async (input, output) => {
    if (!output.system.some((block) => block.includes(LADDER_MARKER))) {
      output.system.push(CHECKBOX_LADDER)
    }
  },
  tool: {
    checkbox: tool({
      description:
        "Run the checkbox Odoo change-policy CLI (bundled, stdlib-only Python). "
        "Call it with a checkbox subcommand plus its CLI arguments, passed "
        "verbatim in the args array -- e.g. command = search, args = [purchase "
        "approval]. Commands: profile show, profile detect, search <query>, "
        "classify <file>, card validate <file>, mode show, ladder render. Add "
        "--json for machine-readable output.",
      args: {
        command: tool.schema.enum(COMMANDS).describe("checkbox subcommand"),
        args: tool.schema
          .array(tool.schema.string())
          .optional()
          .describe("arguments for the subcommand; [] when none"),
      },
      async execute(input, ctx) {
        return await runCli([input.command, ...(input.args ?? [])], ctx.directory)
      },
    }),
  },
  "tool.execute.after": async (input, output) => {
    if (input.tool !== "write" && input.tool !== "edit") return
    const file =
      input.args?.filePath ?? input.args?.path ?? input.args?.file
    if (typeof file !== "string") return
    const tier = await classifyTier(file, directory)
    if (tier) output.title = `checkbox: ${tier}`
  },
})

export default CheckboxPlugin
